In [ ]:
import pandas as pd
import yfinance as yf
from edgar import *
from IPython.display import display
import os
from dotenv import load_dotenv

load_dotenv()
set_identity(os.getenv("EMAIL"))
print("All imported")

In [230]:
def get_companys_datas(acq, tgt, verbose=False):

    acq_dict = yf.Ticker(acq).info

    tgt_dict = yf.Ticker(tgt).info

    if verbose == False:
        pass
    else:
        print(f"{'values':<15} | {acq_dict['symbol']:<25} | {tgt_dict['symbol']:<25}")
        print("-" * 60)
        print(
            f"{'Market cap':<15} | {round(acq_dict['marketCap']):<25,} | {round(tgt_dict['marketCap']):<25,}"
        )
        print(
            f"{'Price':<15} | {acq_dict['previousClose']:<25} | {tgt_dict['previousClose']:<25}"
        )
        print(
            f"{'Shares':<15} | {acq_dict['sharesOutstanding']:<25} | {tgt_dict['sharesOutstanding']:<25}\n\n"
        )

    return acq_dict, tgt_dict


get_companys_datas("AAPL", "NCLH")

({'address1': 'One Apple Park Way',
  'city': 'Cupertino',
  'state': 'CA',
  'zip': '95014',
  'country': 'United States',
  'phone': '(408) 996-1010',
  'website': 'https://www.apple.com',
  'industry': 'Consumer Electronics',
  'industryKey': 'consumer-electronics',
  'industryDisp': 'Consumer Electronics',
  'sector': 'Technology',
  'sectorKey': 'technology',
  'sectorDisp': 'Technology',
  'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
  'fullTimeEmployees': 150000,
  'companyOfficers': [{'maxAge': 1,
    'name': 'Mr. Timothy D. Cook',
    'age': 64,
    'title': 'CEO & Director',
    'yearBorn': 1961,
    'fiscalYear': 2025,
    'totalPay': 16759518,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Kevan  Parekh',
    'age': 53,
    'title': 'Senior VP & CFO',
    'yearBorn': 1972,
    'fiscalYear': 2025,
    'totalPay': 4034174,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Sabih  Khan',
    'age': 58,
    'title': 'Senior VP & Chief Operating Officer',
    'yearBorn': 1967,
    'fiscalYear': 2025,
    'totalPay': 5021905,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': "Ms. Deirdre  O'Brien",
    'age': 58,
    'title': 'Senior Vice President of Retail & People',
    'yearBorn': 1967,
    'fiscalYear': 2025,
    'totalPay': 5037867,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Ms. Katherine L. Adams',
    'age': 61,
    'title': 'Senior VP of Government Affairs & Secretary',
    'yearBorn': 1964,
    'fiscalYear': 2025,
    'totalPay': 5022482,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Ben  Borders',
    'age': 44,
    'title': 'Principal Accounting Officer',
    'yearBorn': 1981,
    'fiscalYear': 2025,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Suhasini  Chandramouli',
    'title': 'Director of Investor Relations',
    'fiscalYear': 2025,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Ms. Jennifer G. Newstead J.D.',
    'age': 54,
    'title': 'Senior VP & General Counsel',
    'yearBorn': 1971,
    'fiscalYear': 2025,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Ms. Kristin Huguet Quayle',
    'title': 'Vice President of Worldwide Communications',
    'fiscalYear': 2025,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Greg  Joswiak',
    'title': 'Senior Vice President of Worldwide Marketing',
    'fiscalYear': 2025,
    'exercisedValue': 0,
    'unexercisedValue': 0}],
  'auditRisk': 2,
  'boardRisk': 1,
  'compensationRisk': 7,
  'shareHolderRightsRisk': 1,
  'overallRisk': 1,
  'governanceEpochDate': 1772323200,
  'compensationAsOfEpochDate': 1767139200,
  'irWebsite': 'http://investor.apple.com/',
  'executiveTeam': [],
  'maxAge': 86400,
  'priceHint': 2,
  'previousClose': 248.96,
  'open': 248.11,
  'dayLow': 246.0,
  'dayHigh': 249.1999,
  'regularMarketPreviousClose': 248.96,
  'regularMarketOpen': 248.11,
  'regularMarketDayLow': 246.0,
  'regularMarketDayHigh': 249.1999,
  'dividendRate': 1.04,
  'dividendYield': 0.42,
  'exDividendDate': 1770595200,
  'payoutRatio': 0.1304,
  'fiveYearAvgDividendYield': 0.52,
  'beta': 1.116,
  'trailingPE': 31.351456,
  'forwardPE': 26.605259,
  'volume': 88331081,
  'regularMarketVolume': 88331081,
  'averageVolume': 46303626,
  'averageVolume10days': 39607800,
  'averageDailyVolume10Day': 39607800,
  'bid': 235.77,
  'ask': 248.06,
  'bidSize': 1,
  'askSize': 1,
  'marketCap': 3644938780672,
  'nonDilutedMarketCap': 3640775908600,
  'fiftyTwoWeekLow': 169.21,
  'fiftyTwoWeekHigh': 288.62,
  'allTimeHigh': 288.62,
  'allTimeLow': 0.049107,
  'priceToSalesTrailing12Months': 8.367301,
  'fiftyDayAverage': 261.13,
  'twoHundredDayAverage': 246.82304,
  'trailingAnnualDividendRate': 1.03,
  'trailingAnnualDividendYield': 0.0041372105,
  'currency': 'USD',
  'tradeable': False,
  'enterpriseValue': 3664377806848,
  'profitMargins': 0.27037,
  'floatShares': 14656182062,
  'sharesOutstanding': 14681140000,
  'sharesShort': 129553812,
  'sharesShortPriorMonth': 116854414,
  'sharesShortPreviousMonthDate': 1769731200,
  'dateShortInterest': 1772150400,
  'sharesPercentSharesOut': 0.0088,
  'heldPercentInsiders': 0.016390001,
  'heldPercentInstitutions': 0.65264,
  'shortRatio': 2.41,
  'shortPercentOfFloat': 0.0088,
  'impliedSharesOutstanding': 14697926000,
  'bookValue': 5.998,
  'priceToBook': 41.345448,
  'lastFiscalYearEnd': 1758931200,
  'nextFiscalYearEnd': 1790467200,
  'mostRecentQuarter': 1766793600,
  'earningsQuarterlyGrowth': 0.159,
  'netIncomeToCommon': 117776998400,
  'trailingEps': 7.91,
  'forwardEps': 9.32109,
  'lastSplitFactor': '4:1',
  'lastSplitDate': 1598832000,
  'enterpriseToRevenue': 8.412,
  'enterpriseToEbitda': 23.966,
  '52WeekChange': 0.123499274,
  'SandP52WeekChange': 0.12811458,
  'lastDividendValue': 0.26,
  'lastDividendDate': 1770595200,
  'quoteType': 'EQUITY',
  'currentPrice': 247.99,
  'targetHighPrice': 350.0,
  'targetLowPrice': 205.0,
  'targetMeanPrice': 295.43536,
  'targetMedianPrice': 300.0,
  'recommendationMean': 1.89583,
  'recommendationKey': 'buy',
  'numberOfAnalystOpinions': 41,
  'totalCash': 66907000832,
  'totalCashPerShare': 4.557,
  'ebitda': 152901992448,
  'totalDebt': 90509000704,
  'quickRatio': 0.845,
  'currentRatio': 0.974,
  'totalRevenue': 435617005568,
  'debtToEquity': 102.63,
  'revenuePerShare': 29.305,
  'returnOnAssets': 0.24377,
  'returnOnEquity': 1.5202099,
  'grossProfits': 206157004800,
  'freeCashflow': 106312753152,
  'operatingCashflow': 135471996928,
  'earningsGrowth': 0.183,
  'revenueGrowth': 0.157,
  'grossMargins': 0.47325,
  'ebitdaMargins': 0.35099998,
  'operatingMargins': 0.35374,
  'financialCurrency': 'USD',
  'symbol': 'AAPL',
  'language': 'en-US',
  'region': 'US',
  'typeDisp': 'Equity',
  'quoteSourceName': 'Nasdaq Real Time Price',
  'triggerable': True,
  'customPriceAlertConfidence': 'HIGH',
  'cryptoTradeable': False,
  'hasPrePostMarketData': True,
  'firstTradeDateMilliseconds': 345479400000,
  'postMarketChangePercent': 0.72986716,
  'postMarketPrice': 249.8,
  'postMarketChange': 1.8099976,
  'regularMarketChange': -0.9700012,
  'regularMarketDayRange': '246.0 - 249.1999',
  'fullExchangeName': 'NasdaqGS',
  'averageDailyVolume3Month': 46303626,
  'fiftyTwoWeekLowChange': 78.78,
  'fiftyTwoWeekLowChangePercent': 0.4655753,
  'fiftyTwoWeekRange': '169.21 - 288.62',
  'fiftyTwoWeekHighChange': -40.62999,
  'fiftyTwoWeekHighChangePercent': -0.1407733,
  'fiftyTwoWeekChangePercent': 12.349928,
  'dividendDate': 1770854400,
  'earningsTimestamp': 1769720400,
  'earningsTimestampStart': 1777579200,
  'earningsTimestampEnd': 1777579200,
  'earningsCallTimestampStart': 1769724000,
  'earningsCallTimestampEnd': 1769724000,
  'isEarningsDateEstimate': True,
  'shortName': 'Apple Inc.',
  'longName': 'Apple Inc.',
  'marketState': 'CLOSED',
  'epsTrailingTwelveMonths': 7.91,
  'epsForward': 9.32109,
  'epsCurrentYear': 8.51182,
  'priceEpsCurrentYear': 29.13478,
  'fiftyDayAverageChange': -13.139999,
  'fiftyDayAverageChangePercent': -0.05031976,
  'twoHundredDayAverageChange': 1.1669617,
  'twoHundredDayAverageChangePercent': 0.0047279284,
  'sourceInterval': 15,
  'exchangeDataDelayedBy': 0,
  'averageAnalystRating': '1.9 - Buy',
  'corporateActions': [],
  'postMarketTime': 1774051191,
  'regularMarketTime': 1774036800,
  'exchange': 'NMS',
  'messageBoardId': 'finmb_24937',
  'exchangeTimezoneName': 'America/New_York',
  'exchangeTimezoneShortName': 'EDT',
  'gmtOffSetMilliseconds': -14400000,
  'market': 'us_market',
  'esgPopulated': False,
  'regularMarketChangePercent': -0.38962132,
  'regularMarketPrice': 247.99,
  'displayName': 'Apple',
  'trailingPegRatio': 2.2029},
 {'address1': '7665 Corporate Center Drive',
  'city': 'Miami',
  'state': 'FL',
  'zip': '33126',
  'country': 'United States',
  'phone': '305 436 4000',
  'fax': '305 436 4140',
  'website': 'https://www.nclhltd.com',
  'industry': 'Travel Services',
  'industryKey': 'travel-services',
  'industryDisp': 'Travel Services',
  'sector': 'Consumer Cyclical',
  'sectorKey': 'consumer-cyclical',
  'sectorDisp': 'Consumer Cyclical',
  'longBusinessSummary': 'Norwegian Cruise Line Holdings Ltd., together with its subsidiaries, operates as a cruise company in North America, Europe, the Asia-Pacific, and internationally. It offers itineraries to destinations, such as Europe, Asia, Australia, New Zealand, South America, Africa, Canada, Bermuda, the Caribbean, and Alaska; and inter-island itinerary in Hawaii. The company also provides features, amenities, and activities, including various accommodations, dining venues, bars and lounges, spas, casino and retail shopping areas, and entertainment choices; shore excursions at each port of call, and air transportation and hotel packages for stays before or after a voyage. It offers its products and services under the Norwegian Cruise Line, Oceania Cruises, and Regent Seven Seas Cruises brands. The company was founded in 1966 and is based in Miami, Florida.',
  'fullTimeEmployees': 44500,
  'companyOfficers': [{'maxAge': 1,
    'name': 'Mr. Mark A. Kempa',
    'age': 53,
    'title': 'Executive VP & CFO',
    'yearBorn': 1972,
    'fiscalYear': 2024,
    'totalPay': 3861531,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Daniel S. Farkas J.D.',
    'age': 56,
    'title': 'Executive VP, General Counsel, Chief Development Officer & Secretary',
    'yearBorn': 1969,
    'fiscalYear': 2024,
    'totalPay': 3199091,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Captain Patrik  Dahlgren',
    'age': 48,
    'title': 'Executive VP and Chief Vessel Operations & Newbuild Officer',
    'yearBorn': 1977,
    'fiscalYear': 2024,
    'totalPay': 2806830,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. John W. Chidsey III, J.D.',
    'age': 61,
    'title': 'President, CEO & Director',
    'yearBorn': 1964,
    'fiscalYear': 2024,
    'totalPay': 1250,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Ms. Faye L. Ashby',
    'age': 53,
    'title': 'Senior VP & Chief Accounting Officer',
    'yearBorn': 1972,
    'fiscalYear': 2024,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Daniel P. Henry',
    'age': 54,
    'title': 'Executive VP and Chief Digital & Technology Officer',
    'yearBorn': 1971,
    'fiscalYear': 2024,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Ms. Sarah  Inmon',
    'title': 'Head of Investor Relations & Corporate Communications',
    'fiscalYear': 2024,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Todd  Hamilton',
    'title': 'Senior Vice President of Sales',
    'fiscalYear': 2024,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Ms. Kiran  Smith',
    'title': 'Chief Marketing Officer',
    'fiscalYear': 2024,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Jason M. Montague',
    'age': 51,
    'title': 'Chief Luxury Officer',
    'yearBorn': 1974,
    'fiscalYear': 2024,
    'totalPay': 4754257,
    'exercisedValue': 0,
    'unexercisedValue': 0}],
  'auditRisk': 10,
  'boardRisk': 4,
  'compensationRisk': 3,
  'shareHolderRightsRisk': 3,
  'overallRisk': 5,
  'governanceEpochDate': 1772323200,
  'compensationAsOfEpochDate': 1735603200,
  'executiveTeam': [],
  'maxAge': 86400,
  'priceHint': 2,
  'previousClose': 19.64,
  'open': 19.45,
  'dayLow': 18.82,
  'dayHigh': 19.5299,
  'regularMarketPreviousClose': 19.64,
  'regularMarketOpen': 19.45,
  'regularMarketDayLow': 18.82,
  'regularMarketDayHigh': 19.5299,
  'payoutRatio': 0.0,
  'beta': 2.044,
  'trailingPE': 20.597826,
  'forwardPE': 7.0899167,
  'volume': 18532953,
  'regularMarketVolume': 18532953,
  'averageVolume': 20910741,
  'averageVolume10days': 21835580,
  'averageDailyVolume10Day': 21835580,
  'bid': 19.02,
  'ask': 19.32,
  'bidSize': 900,
  'askSize': 900,
  'marketCap': 8632590336,
  'nonDilutedMarketCap': 8632589896,
  'fiftyTwoWeekLow': 14.21,
  'fiftyTwoWeekHigh': 27.18,
  'allTimeHigh': 64.27,
  'allTimeLow': 7.03,
  'priceToSalesTrailing12Months': 0.87840337,
  'fiftyDayAverage': 22.0868,
  'twoHundredDayAverage': 22.23595,
  'trailingAnnualDividendRate': 0.0,
  'trailingAnnualDividendYield': 0.0,
  'currency': 'USD',
  'tradeable': False,
  'enterpriseValue': 23958835200,
  'profitMargins': 0.043070003,
  'floatShares': 453099361,
  'sharesOutstanding': 455545641,
  'sharesShort': 35261833,
  'sharesShortPriorMonth': 35837712,
  'sharesShortPreviousMonthDate': 1769731200,
  'dateShortInterest': 1772150400,
  'sharesPercentSharesOut': 0.0774,
  'heldPercentInsiders': 0.00397,
  'heldPercentInstitutions': 0.87157995,
  'shortRatio': 1.53,
  'shortPercentOfFloat': 0.101,
  'impliedSharesOutstanding': 455545641,
  'bookValue': 4.854,
  'priceToBook': 3.9039967,
  'lastFiscalYearEnd': 1767139200,
  'nextFiscalYearEnd': 1798675200,
  'mostRecentQuarter': 1767139200,
  'earningsQuarterlyGrowth': -0.944,
  'netIncomeToCommon': 423246016,
  'trailingEps': 0.92,
  'forwardEps': 2.67281,
  'enterpriseToRevenue': 2.438,
  'enterpriseToEbitda': 9.41,
  '52WeekChange': -0.08409858,
  'SandP52WeekChange': 0.12811458,
  'quoteType': 'EQUITY',
  'currentPrice': 18.95,
  'targetHighPrice': 38.0,
  'targetLowPrice': 19.0,
  'targetMeanPrice': 26.34091,
  'targetMedianPrice': 26.5,
  'recommendationMean': 1.95833,
  'recommendationKey': 'buy',
  'numberOfAnalystOpinions': 22,
  'totalCash': 209892992,
  'totalCashPerShare': 0.461,
  'ebitda': 2546212096,
  'totalDebt': 15536139264,
  'quickRatio': 0.092,
  'currentRatio': 0.209,
  'totalRevenue': 9827592192,
  'debtToEquity': 703.028,
  'revenuePerShare': 21.91,
  'returnOnAssets': 0.045890003,
  'returnOnEquity': 0.23285,
  'grossProfits': 4188429056,
  'freeCashflow': -1548832768,
  'operatingCashflow': 2089746048,
  'revenueGrowth': 0.064,
  'grossMargins': 0.42619,
  'ebitdaMargins': 0.25909,
  'operatingMargins': 0.08315,
  'financialCurrency': 'USD',
  'symbol': 'NCLH',
  'language': 'en-US',
  'region': 'US',
  'typeDisp': 'Equity',
  'quoteSourceName': 'Nasdaq Real Time Price',
  'triggerable': True,
  'customPriceAlertConfidence': 'HIGH',
  'hasPrePostMarketData': True,
  'firstTradeDateMilliseconds': 1358519400000,
  'postMarketChangePercent': 1.3466988,
  'postMarketPrice': 19.2052,
  'postMarketChange': 0.25519943,
  'regularMarketChange': -0.689999,
  'regularMarketDayRange': '18.82 - 19.5299',
  'fullExchangeName': 'NYSE',
  'averageDailyVolume3Month': 20910741,
  'fiftyTwoWeekLowChange': 4.7400007,
  'fiftyTwoWeekLowChangePercent': 0.33356795,
  'fiftyTwoWeekRange': '14.21 - 27.18',
  'fiftyTwoWeekHighChange': -8.23,
  'fiftyTwoWeekHighChangePercent': -0.30279616,
  'fiftyTwoWeekChangePercent': -8.409858,
  'earningsTimestamp': 1772458200,
  'earningsTimestampStart': 1777552200,
  'earningsTimestampEnd': 1777552200,
  'earningsCallTimestampStart': 1772456400,
  'earningsCallTimestampEnd': 1772456400,
  'isEarningsDateEstimate': True,
  'epsTrailingTwelveMonths': 0.92,
  'epsForward': 2.67281,
  'epsCurrentYear': 2.3537,
  'priceEpsCurrentYear': 8.051154,
  'fiftyDayAverageChange': -3.1367989,
  'fiftyDayAverageChangePercent': -0.14202143,
  'twoHundredDayAverageChange': -3.2859497,
  'twoHundredDayAverageChangePercent': -0.14777644,
  'sourceInterval': 15,
  'exchangeDataDelayedBy': 0,
  'averageAnalystRating': '2.0 - Buy',
  'cryptoTradeable': False,
  'shortName': 'Norwegian Cruise Line Holdings ',
  'longName': 'Norwegian Cruise Line Holdings Ltd.',
  'corporateActions': [],
  'postMarketTime': 1774051084,
  'regularMarketTime': 1774036803,
  'exchange': 'NYQ',
  'messageBoardId': 'finmb_4180463',
  'exchangeTimezoneName': 'America/New_York',
  'exchangeTimezoneShortName': 'EDT',
  'gmtOffSetMilliseconds': -14400000,
  'market': 'us_market',
  'esgPopulated': False,
  'regularMarketChangePercent': -3.51323,
  'regularMarketPrice': 18.95,
  'marketState': 'CLOSED',
  'displayName': 'Norwegian Cruise Line',
  'trailingPegRatio': 0.4498})

In [192]:
def contract_offer(
    acq_dict,
    tgt_dict,
    offer_premium=0.60,
    stock_pct=0.50,
    tax_rate=0.40,
    years=5,
    interest_rate=0.05,
    financing_fees_pct=0.035,
    transaccion_fees_pct=0.02,
    synergies_pct=0,
    amortization_years=10,
    verbose=False,
):

    # % of deal pay by cahs and with stocks
    cash_pct = 1 - stock_pct

    # Amount of money the acusition will cost
    share_price = tgt_dict["previousClose"] * (1 + offer_premium)
    offer_value = tgt_dict["sharesOutstanding"] * share_price
    acq_issued_shares = offer_value / acq_dict["previousClose"] * stock_pct

    # All expenses and writre offs
    # Transaccion fees:
    transaccion_fees = offer_value * transaccion_fees_pct
    # Financing fees:
    acq_borrowing = offer_value * cash_pct
    financing_fees = acq_borrowing * financing_fees_pct
    financing_fees_amort = financing_fees / years
    # Posible write of
    synergies = tgt_dict["totalRevenue"] * synergies_pct
    asset_write_off = (offer_value - tgt_dict["bookValue"]) * 0.15
    incremental_DA_expense = asset_write_off / amortization_years

    # Expected earnings
    acq_implide_net_inc = acq_dict["sharesOutstanding"] * acq_dict["epsCurrentYear"]
    tgt_implide_net_inc = tgt_dict["sharesOutstanding"] * tgt_dict["epsCurrentYear"]
    acq_implide_pretax_inc = acq_implide_net_inc / (1 - tax_rate)
    tgt_implide_pretax_inc = tgt_implide_net_inc / (1 - tax_rate)

    # Getting all together and in negatice (accounting reasons)
    profroma_pretax_unadj = acq_implide_pretax_inc + tgt_implide_pretax_inc
    interest_expense_deal = acq_borrowing * interest_rate * -1
    incremental_DA_expense *= -1
    transaccion_fees *= -1
    financing_fees_amort *= -1
    synergies *= 1

    # after merge
    profroma_pretax_adj = (
        profroma_pretax_unadj
        + interest_expense_deal
        + incremental_DA_expense
        + transaccion_fees
        + financing_fees_amort
        + synergies
    )
    proforma_net_income = profroma_pretax_adj * (1 - tax_rate)
    proforma_shares_outstanding = acq_dict["sharesOutstanding"] + acq_issued_shares
    proforma_eps = proforma_net_income / proforma_shares_outstanding
    accretion_dilution_per_share = proforma_eps - acq_dict["epsCurrentYear"]
    accretion_dilution_pct = (proforma_eps / acq_dict["epsCurrentYear"]) - 1

    if verbose == False:
        pass
    else:
        print("Parameters:")
        print(f"Offer premium:            | {offer_premium * 100}%")
        print(f"% of cash:                | {cash_pct * 100}%")
        print(f"% of stock:               | {stock_pct * 100}%")
        print(f"tax rate:                 | {tax_rate * 100}%")
        print(f"interest rate:            | {interest_rate * 100}%")
        print(f"% financing fees:         | {transaccion_fees_pct * 100}%")
        print(f"% transaccion fees:       | {transaccion_fees_pct * 100}%")
        print(f"% synergies:              | {synergies_pct * 100}%")
        print(f"{'-' * 60}\n")

        print("Deal:")
        print(f"Share price:              | {round(share_price):,}")
        print(f"Offer Value:              | {round(offer_value):,}")
        print(f"Money borrowed:           | {round(acq_borrowing):,}")
        print(f"Financing fees:           | {round(financing_fees):,}")
        print(f"Shares issued:            | {round(acq_issued_shares):,}\n")
        print(f"{'-' * 60}\n")

        print("Income:")
        print(f"Accuary net income:       | {round(acq_implide_net_inc):,}")
        print(f"Target net income:        | {round(tgt_implide_net_inc):,}")
        print(f"Accuary pre tax income:   | {round(acq_implide_pretax_inc):,}")
        print(f"Target pre tax income:    | {round(tgt_implide_pretax_inc):,}")
        print(f"{'-' * 60}\n")

        print("Totals")
        print(f"Proforma pretax unadj:    | {round(profroma_pretax_unadj):,}")
        print(f"Interest expenses:        | ({round(interest_expense_deal * -1):,})")
        print(f"Amort of finance fees:    | ({round(financing_fees_amort * -1):,})")
        print(f"Transaccion fees:         | ({round(transaccion_fees * -1):,})")
        print(f"D/A write off:            | ({round(incremental_DA_expense * -1):,})")
        print(f"% synergies:              | {round(synergies):,}")
        print(f"{'-' * 60}\n")

        print("After merge:")
        print(f"Proforma pretax adj:      | {round(profroma_pretax_adj):,}")
        print(f"Proforma Net:             | {round(proforma_net_income):,}")
        print(f"Proforma shares:          | {round(proforma_shares_outstanding):,}")
        print(f"Proforma eps:             | {round(proforma_eps, ndigits=2)}")
        print(f"{'-' * 60}\n")

        print("Results")
        print(f"Accretion/Dilution:       | $ {accretion_dilution_per_share:.2f}")
        print(f"%Accretion/Dilution:      | % {accretion_dilution_pct:.2f}")

    return accretion_dilution_pct

In [189]:
acq, tgt = get_companys_datas("AAPL", "SPOT")

contract_offer(acq, tgt, offer_premium=0.30, verbose=False)

values          | AAPL                      | SPOT
------------------------------------------------------------
Market cap      | 3,644,938,780,672         | 97,704,951,808
Price           | 248.96                    | 482.52
Shares          | 14681140000               | 205832527

-0.03492217175138612

In [272]:
def highlight_irr(val):
    if val >= 0:
        return "background-color: #d4edda !important; color: black !important"
    elif val >= -0.05:
        return "background-color: #fff3cd !important; color: black !important"
    else:
        return "background-color: #f8d7da !important; color: black !important"


def sensitivity_accretion_dilution(acq, tgt, verbose=False, steps=1):

    rows = []
    for i in range(0, 11, steps):
        row = []
        for j in range(0, 11, steps):
            accretion_dilution_pct = round(
                contract_offer(
                    acq, tgt, offer_premium=i / 10, stock_pct=j / 10, verbose=False
                ),
                ndigits=2,
            )

            row.append(accretion_dilution_pct)

        rows.append(row)

    df = df = pd.DataFrame(
        rows,
        columns=[f"Stock {x * 10}%" for x in range(0, 11, steps)],
        index=[f"Offer premium {x * 10}%" for x in range(0, 11, steps)],
    )
    styled = df.style.format("{:.2f}%").map(highlight_irr)
    display(styled)

    return df

In [273]:
def highlight_irr(val):
    if val >= 0:
        return "background-color: #d4edda !important; color: black !important"
    elif val >= -0.05:
        return "background-color: #fff3cd !important; color: black !important"
    else:
        return "background-color: #f8d7da !important; color: black !important"

In [274]:
acq, tgt = get_companys_datas("SONO", "NCLH")
sensitivity_accretion_dilution(acq, tgt, verbose=False, steps=1)

,Stock 0%,Stock 10%,Stock 20%,Stock 30%,Stock 40%,Stock 50%,Stock 60%,Stock 70%,Stock 80%,Stock 90%,Stock 100%
Offer premium 0%,4.31,2.57,1.74,1.26,0.94,0.72,0.55,0.42,0.32,0.24,0.17
Offer premium 10%,3.94,2.23,1.46,1.02,0.74,0.54,0.39,0.28,0.19,0.12,0.06
Offer premium 20%,3.57,1.92,1.21,0.81,0.56,0.38,0.25,0.15,0.08,0.01,-0.04
Offer premium 30%,3.21,1.62,0.97,0.62,0.39,0.24,0.13,0.04,-0.02,-0.08,-0.12
Offer premium 40%,2.84,1.35,0.76,0.45,0.25,0.12,0.02,-0.05,-0.11,-0.16,-0.19
Offer premium 50%,2.47,1.09,0.57,0.29,0.12,0.01,-0.07,-0.14,-0.18,-0.22,-0.26
Offer premium 60%,2.10,0.84,0.39,0.15,0.01,-0.09,-0.16,-0.21,-0.25,-0.29,-0.31
Offer premium 70%,1.73,0.61,0.22,0.02,-0.10,-0.18,-0.24,-0.28,-0.31,-0.34,-0.36
Offer premium 80%,1.37,0.39,0.07,-0.10,-0.19,-0.26,-0.31,-0.34,-0.37,-0.39,-0.41
Offer premium 90%,1.00,0.19,-0.07,-0.20,-0.28,-0.33,-0.37,-0.40,-0.42,-0.43,-0.45
Offer premium 100%,0.63,-0.01,-0.21,-0.30,-0.36,-0.40,-0.43,-0.45,-0.46,-0.47,-0.49

In [275]:
acq, tgt = get_companys_datas("AAPL", "SPOT")
sensitivity_accretion_dilution(acq, tgt, verbose=False, steps=2)

,Stock 0%,Stock 20%,Stock 40%,Stock 60%,Stock 80%,Stock 100%
Offer premium 0%,-0.02,-0.02,-0.02,-0.02,-0.02,-0.02
Offer premium 20%,-0.03,-0.03,-0.03,-0.03,-0.03,-0.03
Offer premium 40%,-0.04,-0.04,-0.04,-0.04,-0.04,-0.04
Offer premium 60%,-0.05,-0.05,-0.05,-0.05,-0.05,-0.05
Offer premium 80%,-0.06,-0.06,-0.06,-0.06,-0.06,-0.05
Offer premium 100%,-0.07,-0.07,-0.06,-0.06,-0.06,-0.06

In [276]:
def accretion_dilution_model(acq, tgt):
    acq_dict, tgt_dict = get_companys_datas(acq, tgt, verbose=True)
    contract_offer(acq_dict, tgt_dict, verbose=True)
    sensitivity_accretion_dilution(acq_dict, tgt_dict)

In [277]:
accretion_dilution_model("AAPl", "NCLH")

values          | AAPL                      | NCLH
------------------------------------------------------------
Market cap      | 3,644,938,780,672         | 8,632,590,336
Price           | 248.96                    | 19.64
Shares          | 14681140000               | 455545641


Parameters:
Offer premium:            | 60.0%
% of cash:                | 50.0%
% of stock:               | 50.0%
tax rate:                 | 40.0%
interest rate:            | 5.0%
% financing fees:         | 2.0%
% transaccion fees:       | 2.0%
% synergies:              | 0%
------------------------------------------------------------

Deal:
Share price:              | 31
Offer Value:              | 14,315,066,223
Money borrowed:           | 7,157,533,111
Financing fees:           | 250,513,659
Shares issued:            | 28,749,731

------------------------------------------------------------

Income:
Accuary net income:       | 124,963,221,075
Target net income:        | 1,072,217,775
Accuary pre tax income:   | 208,272,035,125
Target pre tax income:    | 1,787,029,625
------------------------------------------------------------

Totals
Proforma pretax unadj:    | 210,059,064,750
Interest expenses:        | (357,876,656)
Amort of finance fees:    | (50,102,732)
Transaccion fees:         | (286,301,324)
D/A write off:            | (214,725,993)
% synergies:              | 0
------------------------------------------------------------

After merge:
Proforma pretax adj:      | 209,150,058,045
Proforma Net:             | 125,490,034,827
Proforma shares:          | 14,709,889,731
Proforma eps:             | 8.53
------------------------------------------------------------

Results
Accretion/Dilution:       | $ 0.02
%Accretion/Dilution:      | % 0.00

In [38]:
tgt_ticker = yf.Ticker("NCLH")
for i in tgt_ticker.info:
    print(i)

address1
city
state
zip
country
phone
fax
website
industry
industryKey
industryDisp
sector
sectorKey
sectorDisp
longBusinessSummary
fullTimeEmployees
companyOfficers
auditRisk
boardRisk
compensationRisk
shareHolderRightsRisk
overallRisk
governanceEpochDate
compensationAsOfEpochDate
executiveTeam
maxAge
priceHint
previousClose
open
dayLow
dayHigh
regularMarketPreviousClose
regularMarketOpen
regularMarketDayLow
regularMarketDayHigh
payoutRatio
beta
trailingPE
forwardPE
volume
regularMarketVolume
averageVolume
averageVolume10days
averageDailyVolume10Day
bid
ask
bidSize
askSize
marketCap
nonDilutedMarketCap
fiftyTwoWeekLow
fiftyTwoWeekHigh
allTimeHigh
allTimeLow
priceToSalesTrailing12Months
fiftyDayAverage
twoHundredDayAverage
trailingAnnualDividendRate
trailingAnnualDividendYield
currency
tradeable
enterpriseValue
profitMargins
floatShares
sharesOutstanding
sharesShort
sharesShortPriorMonth
sharesShortPreviousMonthDate
dateShortInterest
sharesPercentSharesOut
heldPercentInsiders
heldPercentInstitutions
shortRatio
shortPercentOfFloat
impliedSharesOutstanding
bookValue
priceToBook
lastFiscalYearEnd
nextFiscalYearEnd
mostRecentQuarter
earningsQuarterlyGrowth
netIncomeToCommon
trailingEps
forwardEps
enterpriseToRevenue
enterpriseToEbitda
52WeekChange
SandP52WeekChange
quoteType
currentPrice
targetHighPrice
targetLowPrice
targetMeanPrice
targetMedianPrice
recommendationMean
recommendationKey
numberOfAnalystOpinions
totalCash
totalCashPerShare
ebitda
totalDebt
quickRatio
currentRatio
totalRevenue
debtToEquity
revenuePerShare
returnOnAssets
returnOnEquity
grossProfits
freeCashflow
operatingCashflow
revenueGrowth
grossMargins
ebitdaMargins
operatingMargins
financialCurrency
symbol
language
region
typeDisp
quoteSourceName
triggerable
customPriceAlertConfidence
marketState
hasPrePostMarketData
firstTradeDateMilliseconds
regularMarketChange
regularMarketDayRange
fullExchangeName
averageDailyVolume3Month
fiftyTwoWeekLowChange
fiftyTwoWeekLowChangePercent
fiftyTwoWeekRange
fiftyTwoWeekHighChange
fiftyTwoWeekHighChangePercent
fiftyTwoWeekChangePercent
earningsTimestamp
earningsTimestampStart
earningsTimestampEnd
earningsCallTimestampStart
earningsCallTimestampEnd
isEarningsDateEstimate
epsTrailingTwelveMonths
epsForward
epsCurrentYear
priceEpsCurrentYear
fiftyDayAverageChange
fiftyDayAverageChangePercent
twoHundredDayAverageChange
twoHundredDayAverageChangePercent
sourceInterval
exchangeDataDelayedBy
averageAnalystRating
cryptoTradeable
corporateActions
regularMarketTime
exchange
messageBoardId
exchangeTimezoneName
exchangeTimezoneShortName
gmtOffSetMilliseconds
market
esgPopulated
regularMarketChangePercent
regularMarketPrice
shortName
longName
displayName
trailingPegRatio

In [72]:
acq, tgt = get_companys_datas("AAPL", "SPOT")
contract_offer(acq, tgt, offer_premium=0.30)

-----AAPL Acquirer---------------
Market cap is 3,644,938,780,672, with 14681140000 shares valued at 249.0$
With and EPS of 8.51182,and this 435617005568

-----SPOT Acquirer---------------
Market cap is 97,704,951,808, with 205832527 shares valued at 482.5$
With and EPS of 13.04623,and this 17186000896

Net accretion_dilution_per_share-0.29725123995688385 wich is -0.03492217175138612

In [64]:
dict_a = yf.Ticker("AAPl").info
dict_a

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 54,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 248.96,
 'open': 248.11,
 'dayLow': 246.0,
 'dayHigh': 249.1999,
 'regularMarketPreviousClose': 248.96,
 'regularMarketOpen': 248.11,
 'regularMarketDayLow': 246.0,
 'regularMarketDayHigh': 249.1999,
 'dividendRate': 1.04,
 'dividendYield': 0.42,
 'exDividendDate': 1770595200,
 'payoutRatio': 0.1304,
 'fiveYearAvgDividendYield': 0.52,
 'beta': 1.116,
 'trailingPE': 31.351456,
 'forwardPE': 26.605259,
 'volume': 87981315,
 'regularMarketVolume': 87981315,
 'averageVolume': 46144088,
 'averageVolume10days': 39607800,
 'averageDailyVolume10Day': 39607800,
 'bid': 235.77,
 'ask': 248.06,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 3644938780672,
 'nonDilutedMarketCap': 3640775908600,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 8.367301,
 'fiftyDayAverage': 261.13,
 'twoHundredDayAverage': 246.82304,
 'trailingAnnualDividendRate': 1.03,
 'trailingAnnualDividendYield': 0.0041372105,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3664377806848,
 'profitMargins': 0.27037,
 'floatShares': 14656182062,
 'sharesOutstanding': 14681140000,
 'sharesShort': 129553812,
 'sharesShortPriorMonth': 116854414,
 'sharesShortPreviousMonthDate': 1769731200,
 'dateShortInterest': 1772150400,
 'sharesPercentSharesOut': 0.0088,
 'heldPercentInsiders': 0.016390001,
 'heldPercentInstitutions': 0.65264,
 'shortRatio': 2.41,
 'shortPercentOfFloat': 0.0088,
 'impliedSharesOutstanding': 14697926000,
 'bookValue': 5.998,
 'priceToBook': 41.345448,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1766793600,
 'earningsQuarterlyGrowth': 0.159,
 'netIncomeToCommon': 117776998400,
 'trailingEps': 7.91,
 'forwardEps': 9.32109,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.412,
 'enterpriseToEbitda': 23.966,
 '52WeekChange': 0.123499274,
 'SandP52WeekChange': 0.12811458,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1770595200,
 'quoteType': 'EQUITY',
 'currentPrice': 247.99,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 295.43536,
 'targetMedianPrice': 300.0,
 'recommendationMean': 1.89583,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 41,
 'totalCash': 66907000832,
 'totalCashPerShare': 4.557,
 'ebitda': 152901992448,
 'totalDebt': 90509000704,
 'quickRatio': 0.845,
 'currentRatio': 0.974,
 'totalRevenue': 435617005568,
 'debtToEquity': 102.63,
 'revenuePerShare': 29.305,
 'returnOnAssets': 0.24377,
 'returnOnEquity': 1.5202099,
 'grossProfits': 206157004800,
 'freeCashflow': 106312753152,
 'operatingCashflow': 135471996928,
 'earningsGrowth': 0.183,
 'revenueGrowth': 0.157,
 'grossMargins': 0.47325,
 'ebitdaMargins': 0.35099998,
 'operatingMargins': 0.35374,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'epsTrailingTwelveMonths': 7.91,
 'epsForward': 9.32109,
 'epsCurrentYear': 8.51182,
 'priceEpsCurrentYear': 29.13478,
 'fiftyDayAverageChange': -13.139999,
 'fiftyDayAverageChangePercent': -0.05031976,
 'twoHundredDayAverageChange': 1.1669617,
 'twoHundredDayAverageChangePercent': 0.0047279284,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.9 - Buy',
 'cryptoTradeable': False,
 'regularMarketChangePercent': -0.389621,
 'regularMarketPrice': 247.99,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'marketState': 'CLOSED',
 'corporateActions': [],
 'postMarketTime': 1774051191,
 'regularMarketTime': 1774036800,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': 0.72986716,
 'postMarketPrice': 249.8,
 'postMarketChange': 1.8099976,
 'regularMarketChange': -0.970001,
 'regularMarketDayRange': '246.0 - 249.1999',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 46144088,
 'fiftyTwoWeekLowChange': 78.78,
 'fiftyTwoWeekLowChangePercent': 0.4655753,
 'fiftyTwoWeekRange': '169.21 - 288.62',
 'fiftyTwoWeekHighChange': -40.62999,
 'fiftyTwoWeekHighChangePercent': -0.1407733,
 'fiftyTwoWeekChangePercent': 12.349928,
 'dividendDate': 1770854400,
 'earningsTimestamp': 1769720400,
 'earningsTimestampStart': 1777579200,
 'earningsTimestampEnd': 1777579200,
 'earningsCallTimestampStart': 1769724000,
 'earningsCallTimestampEnd': 1769724000,
 'isEarningsDateEstimate': True,
 'displayName': 'Apple',
 'trailingPegRatio': 2.2029}